version: '3'

services:
  web:
    build: ./
    restart: always
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    ports:
      - "8000:8000"

  redis:
    image: redis
    ports:
      - "6379:6379"

  beat_worker:
    restart: unless-stopped
    build:
      context: .
    command: celery -A spoton beat -l INFO
    volumes:
      - ./:/app
    depends_on:
      - redis
      - web

  celery_worker:
    restart: unless-stopped
    build:
      context: .
    command: celery -A spoton worker -l INFO
    volumes:
      - ./:/app
    depends_on:
      - redis
      - web

